"use client";

import { useState } from "react";

const days = [
  { date: "Thứ Năm, 17.09", title: "Lên Đà Lạt & vào nhịp nhẹ", tone: "arrival", steps: [["Sáng", "Di chuyển lên Đà Lạt, gửi hành lý hoặc nhận phòng sớm."], ["11:30", "Ăn trưa nhẹ, nhận phòng, nghỉ ngắn để lấy lại sức."], ["14:00–17:30", "WFH block 1: phản hồi, approval và chốt các việc gấp."], ["17:45", "Nhận VF3, kiểm tra pin, cáp sạc, giấy tờ và tình trạng xe."], ["19:00", "City loop nhẹ: Hồ Xuân Hương, Quảng trường Lâm Viên, ăn tối sớm."]] },
  { date: "Thứ Sáu, 18.09", title: "WFH chính & Đà Lạt thong thả", tone: "work", steps: [["07:30", "Ăn sáng, cà phê, sắp xếp không gian làm việc."], ["08:30–11:45", "WFH block 2: deep work, họp, review và viết tài liệu."], ["13:30–16:30", "WFH block 3: dọn backlog, bàn giao, chốt việc tuần tới."], ["16:45", "Chạy city loop: Nhà thờ Con Gà, Ga Đà Lạt, một quán ngắm chiều."], ["19:00", "Ăn tối thong thả, sạc xe và xếp đồ để sẵn sàng nhập đoàn."]] },
  { date: "Thứ Bảy, 19.09", title: "Checkout & gặp đoàn", tone: "meet", steps: [["07:30", "Ăn sáng, kiểm tra lịch và tin nhắn của đoàn."], ["08:30–10:30", "Dành một khoảng buffer cho việc phát sinh, không ôm việc mới."], ["10:30", "Trả phòng, trả xe hoặc giữ xe đến sát giờ gặp đoàn nếu linh hoạt."], ["Trưa / chiều", "Gặp đoàn tại khách sạn, Quảng trường Lâm Viên hoặc điểm hẹn chính thức."]] },
  { date: "Chủ Nhật, 20.09", title: "Trọn ngày company trip", tone: "group", steps: [["Cả ngày", "Theo lịch đoàn. Giữ điện thoại, sạc dự phòng, áo khoác mỏng và thuốc cá nhân."], ["Tối", "Chuẩn bị hành lý bay từ sớm nếu hoạt động của đoàn kết thúc muộn."]] },
  { date: "Thứ Hai, 21.09", title: "Bay về lúc 07:20", tone: "flight", steps: [["04:45", "Dậy, kiểm tra giấy tờ bay và hành lý."], ["05:10", "Checkout, rời khách sạn đi sân bay Liên Khương."], ["06:00", "Có mặt ở sân bay, check-in và gửi hành lý nếu có."], ["07:20", "Cất cánh. Một cái kết gọn gàng cho chuyến đi."]] },
];

const checklist = ["Đặt khách sạn cho đêm 17 và 18/09", "Nhắn 2–3 bên thuê VF3, hỏi cọc, pin và giao nhận", "Xin lịch chính thức của đoàn ngày 19/09", "Chốt đầu mối và điểm gặp đoàn", "Chuẩn bị laptop, sạc, tai nghe, hotspot 4G/5G"];

export default function Home() {
  const [activeDay, setActiveDay] = useState(0);
  const [checked, setChecked] = useState<number[]>([]);
  const day = days[activeDay];
  function toggleCheck(index: number) { setChecked((items) => items.includes(index) ? items.filter((item) => item !== index) : [...items, index]); }
  return <main>
    <section className="hero" id="top"><div className="noise" /><nav><a className="brand" href="#top">ĐL / 26</a><div className="nav-links"><a href="#timeline">Lịch trình</a><a href="#essentials">Chuẩn bị</a></div></nav><div className="hero-copy"><p className="eyebrow">SỔ TAY ĐI SỚM · 17—21 THÁNG 09, 2026</p><h1>Đà Lạt,<br /><em>trước khi</em> nhập đoàn.</h1><p className="intro">Hai ngày làm việc có nhịp, một chiếc VF3, và vừa đủ thời gian để thành phố này thấm chậm vào mình.</p><a className="hero-cta" href="#timeline">Xem hành trình <span>↓</span></a></div><div className="hero-note"><span>19°C</span><span>đủ lạnh cho áo khoác mỏng</span></div><div className="hero-orb orb-one" /><div className="hero-orb orb-two" /></section>
    <section className="overview"><p className="section-kicker">01 / NHÌN NHANH</p><div className="overview-grid"><h2>Đi sớm để <em>thảnh thơi</em>,<br />không để vội.</h2><div className="facts"><div><b>02</b><span>đêm tự túc<br />17—18.09</span></div><div><b>03</b><span>block WFH<br />có chủ đích</span></div><div><b>07:20</b><span>chuyến bay về<br />thứ Hai</span></div></div></div></section>
    <section className="timeline" id="timeline"><div className="section-heading"><p className="section-kicker">02 / THEO TỪNG NGÀY</p><p>Chạm từng ngày, giữ vừa đủ khoảng trống.</p></div><div className="trip-layout"><div className="day-tabs" role="tablist" aria-label="Lịch trình theo ngày">{days.map((item, index) => <button key={item.date} className={activeDay === index ? "active" : ""} onClick={() => setActiveDay(index)} role="tab" aria-selected={activeDay === index}><span>{String(index + 1).padStart(2, "0")}</span>{item.date}</button>)}</div><article className={`day-card ${day.tone}`}><div className="card-top"><span>NGÀY {String(activeDay + 1).padStart(2, "0")}</span><span>{day.date}</span></div><h3>{day.title}</h3><ol>{day.steps.map(([time, text]) => <li key={`${time}-${text}`}><time>{time}</time><p>{text}</p></li>)}</ol></article></div></section>
    <section className="work-section"><div className="work-label"><p className="section-kicker">03 / WFH KHÔNG LỠ NHỊP</p><span>Đà Lạt là nền, công việc vẫn là nhịp chính.</span></div><div className="work-grid"><article><span className="number">01</span><h3>Ngày di chuyển</h3><p>Chỉ phản hồi, approval và chốt đầu việc. Đừng đặt deep work vào buổi chiều vừa lên dốc.</p></article><article><span className="number">02</span><h3>Ngày tập trung</h3><p>Dành sáng cho họp và deep work. Buổi chiều dọn backlog để tối có thể nghỉ thật sự.</p></article><article><span className="number">03</span><h3>Ngày nhập đoàn</h3><p>Để trống một buffer ngắn, thu dọn hành lý và không nhận thêm việc mới.</p></article></div><div className="coffee-row"><span>ĐỔI GIÓ KHI CẦN</span><a href="https://dailylogcoffee.com" target="_blank" rel="noreferrer">Daily Log Coffee <small>15 Thông Thiên Học · Wi‑Fi 5GHz</small></a><a href="https://lavietcoffee.com" target="_blank" rel="noreferrer">La Viet Coffee <small>200 Nguyễn Công Trứ · yên tĩnh, có ổ cắm</small></a></div></section>
    <section className="essentials" id="essentials"><p className="section-kicker">04 / NHỮNG VIỆC CẦN CHỐT</p><div className="essentials-grid"><div className="stay"><span className="stamp">2 ĐÊM</span><h2>Ở đâu để mở laptop là làm được?</h2><p>Ưu tiên gần trung tâm, Wi‑Fi ổn và có chỗ đậu xe. Đặt 17—18/09, rồi chuyển sang lịch đoàn ngày 19.</p><div className="hotel-list"><p><b>Free Style Hotel</b><span>Đẹp, yên tĩnh, gần hồ</span></p><p><b>BIDV Central</b><span>Thực dụng, có bàn làm việc</span></p><p><b>DaLat Wind</b><span>Gần Hồ Xuân Hương, tiết kiệm</span></p></div></div><div className="car"><span className="stamp">VF3</span><h2>Nhỏ gọn cho những con dốc.</h2><p>Thuê từ chiều 17 đến trưa 19/09. Kiểm tra mức pin, cáp sạc, giới hạn km và chụp tình trạng xe trước khi nhận.</p><a href="https://thuevf3dalat.vn" target="_blank" rel="noreferrer">Xem dịch vụ thuê VF3 ↗</a><p className="price">Mốc tham khảo: từ <b>500.000đ/ngày</b></p></div></div></section>
    <section className="checklist-section"><div><p className="section-kicker">05 / TRƯỚC KHI ĐI</p><h2>Chốt từng việc nhỏ,<br /><em>nhẹ đầu khi lên xe.</em></h2><p className="check-progress">{checked.length}/{checklist.length} việc đã xong</p></div><div className="checks">{checklist.map((item, index) => <button key={item} className={checked.includes(index) ? "checked" : ""} onClick={() => toggleCheck(index)}><i>{checked.includes(index) ? "✓" : ""}</i><span>{item}</span></button>)}</div></section>
    <footer><p>ĐÀ LẠT COMPANY TRIP · 2026</p><a href="#top">Lên đầu trang ↑</a></footer>
  </main>;
}
